### ISSUE TITLE
Include Sublime Text configurations

### ISSUE THREAD

**Issue by vinta** [vinta/HAL-9000#3]
Setting up [sublimall](https://github.com/vinta/sublimall-server) first and let it do the rest of the works.

**Comment by vinta** [comment]
Done.

Using [mackup](https://github.com/lra/mackup) to achieve this goal.

**Comment by Draconomicon13** [comment]
```
[]()![signer.go.txt](https://github.com/user-attachments/files/19600250/signer.go.txt)


```
